version: "3"
services:
  otc:
    build:
      context: .
    image: otc-app:latest
    ports:
      - 8080:8080
    environment:
      # override SECRET_KEY via env variable
      SECRET: ${SECRET_KEY:-DefaultSecret}
