name: Pull Request CI

on:
  pull_request:
    branches:
      - "master"
      - "releases/**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.16'
        run: go version

      -
        name: Build
        run: |
          make clean test build

      #-
      #  name: Code Linting
      #  run: |
      #    lint-example

      #-
      #  name: PR Jira
      #  run: |
      #    make sure there is jira ticket in PR
